import "./App.css";

export const pokemonType = [
  {type: "Fire", color: "#EE8130"}, 
  {type: "Water", color: "#6390F0"}, 
  {type: "Grass", color: "#7AC74C"}, 
  {type: "Ground", color: "#E2BF65"}, 
  {type: "Psychic", color: "#F95587"}, 
  {type: "Ghost", color: "#735797"}, 
  {type: "Fighting", color: "#C22E28"}, 
  {type: "Dragon", color: "#6F35FC"}, 
  {type: "Poison", color: "#A33EA1"}, 
  {type: "Normal", color: "#A8A77A"}, 
  {type: "Electric", color: "#F7D02C"}
];

export const pokemonFire = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/charizard.gif',
    num: 1,
    name: "Charizard",
    type: "Fire",
    hp: 360,
    maxHp: 360,
    atk: 348,
    spd: 328,
    moves: ["Flamethrower", "Dragon Breath", "Air Slash", "Fire Blast"],
    moveType: ["Fire", "Dragon", "Flying", "Fire"],
    moveDmg: [90, 60, 75, 110],
    moveAccuracy: [100, 100, 95, 85],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/ninetales.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/ninetales.gif',
    num: 2,
    name: "Ninetales",
    type: "Fire",
    hp: 349,
    maxHp: 349,
    atk: 250,
    spd: 298,
    moves: ["Flamethrower", "Dragon Breath", "Hyper Beam", "Dig"],
    moveType: ["Fire", "Dragon", "Normal", "Ground"],
    moveDmg: [90, 60, 150, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/arcanine.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/arcanine.gif',
    num: 3,
    name: "Arcanine",
    type: "Fire",
    hp: 383,
    maxHp: 383,
    atk: 318,
    spd: 288,
    moves: ["Flamethrower", "Dragon Rage", "Take Down", "Dig"],
    moveType: ["Fire", "Dragon", "Normal", "Ground"],
    moveDmg: [90, 90, 90, 100],
    moveAccuracy: [100, 100, 85, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/rapidash.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/rapidash.gif',
    num: 4,
    name: "Rapidash",
    type: "Fire",
    hp: 333,
    maxHp: 333,
    atk: 298,
    spd: 308,
    moves: ["Flamethrower", "Ember", "Swift", "Dig"],
    moveType: ["Fire", "Fire", "Normal", "Ground"],
    moveDmg: [90, 40, 60, 100],
    moveAccuracy: [100, 100, 100, 100],
  },
];

export const pokemonWater = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/blastoise.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/blastoise.gif',
    num: 5,
    name: "Blastoise",
    type: "Water",
    hp: 364,
    maxHp: 364,
    atk: 328,
    spd: 284,
    moves: ["Hydro Pump", "Aqua Tail", "Flash Cannon", "Earthquake"],
    moveType: ["Water", "Water", "Steel", "Ground"],
    moveDmg: [110, 90, 80, 100],
    moveAccuracy: [80, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/golduck.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/golduck.gif',
    num: 6,
    name: "Golduck",
    type: "Water",
    hp: 363,
    maxHp: 363,
    atk: 262,
    spd: 268,
    moves: ["Surf", "Aqua Tail", "Submission", "Dig"],
    moveType: ["Water", "Water", "Fighting", "Ground"],
    moveDmg: [95, 90, 80, 100],
    moveAccuracy: [100, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwrath.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/poliwrath.gif',
    num: 7,
    name: "Poliwrath",
    type: "Water",
    hp: 383,
    maxHp: 383,
    atk: 268,
    spd: 238,
    moves: ["Surf", "Ice Beam", "Submission", "Fissure"],
    moveType: ["Water", "Ice", "Fighting", "Ground"],
    moveDmg: [95, 90, 80, 80],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/tentacruel.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/tentacruel.gif',
    num: 8,
    name: "Tentacruel",
    type: "Water",
    hp: 346,
    maxHp: 346,
    atk: 238,
    spd: 298,
    moves: ["Surf", "Ice Beam", "Hydro Pump", "Sludge Bomb"],
    moveType: ["Water", "Ice", "Water", "Poison"],
    moveDmg: [95, 90, 120, 80],
    moveAccuracy: [100, 100, 80, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/slowbro.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/slowbro.gif',
    num: 9,
    name: "Slowbro",
    type: "Water",
    hp: 439,
    maxHp: 439,
    atk: 248,
    spd: 158,
    moves: ["Surf", "Ice Beam", "Thunder Wave", "Psychic"],
    moveType: ["Water", "Ice", "Electric", "Psychic"],
    moveDmg: [95, 90, 90, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dewgong.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dewgong.gif',
    num: 10,
    name: "Dewgong",
    type: "Water",
    hp: 383,
    maxHp: 383,
    atk: 238,
    spd: 345,
    moves: ["Surf", "Ice Beam", "Aurora Beam", "Psychic"],
    moveType: ["Water", "Ice", "Ice", "Psychic"],
    moveDmg: [95, 90, 65, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/cloyster.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/cloyster.gif',
    num: 11,
    name: "Cloyster",
    type: "Water",
    hp: 303,
    maxHp: 303,
    atk: 288,
    spd: 219,
    moves: ["Surf", "Ice Beam", "Blizzard", "Hyper Beam"],
    moveType: ["Water", "Ice", "Ice", "Normal"],
    moveDmg: [95, 90, 120, 120],
    moveAccuracy: [100, 100, 100, 75],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/gyarados.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/gyrados.gif',
    num: 12,
    name: "Gyarados",
    type: "Water",
    hp: 477,
    maxHp: 477,
    atk: 399,
    spd: 232,
    moves: ["Hurricane", "Outrage", "Hydro Pump", "Hyper Beam"],
    moveType: ["Flying", "Dragon", "Water", "Normal"],
    moveDmg: [110, 120, 120, 120],
    moveAccuracy: [70, 100, 80, 75],
  },
];

export const pokemonGrass = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/venusaur.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/venusaur.gif',
    num: 13,
    name: "Venusaur",
    type: "Grass",
    hp: 400,
    maxHp: 400,
    atk: 295,
    spd: 280,
    moves: ["Petal Blizzard", "Sludge", "Skull Bash", "Earthquake"],
    moveType: ["Grass", "Poison", "Normal", "Ground"],
    moveDmg: [90, 65, 130, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/vileplume.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/vileplume.gif',
    num: 14,
    name: "Vileplume",
    type: "Grass",
    hp: 353,
    maxHp: 353,
    atk: 358,
    spd: 198,
    moves: ["Solar Beam", "Sludge", "Skull Bash", "Acid"],
    moveType: ["Grass", "Poison", "Normal", "Poison"],
    moveDmg: [120, 65, 130, 40],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/victreebel.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/victreebel.gif',
    num: 15,
    name: "Victreebel",
    type: "Grass",
    hp: 363,
    maxHp: 363,
    atk: 308,
    spd: 238,
    moves: ["Mega Drain", "Razor Leaf", "Skull Bash", "Acid"],
    moveType: ["Grass", "Grass", "Normal", "Poison"],
    moveDmg: [80, 95, 130, 40],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/exeggutor.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/exeggutor.gif',
    num: 16,
    name: "Exeggutor",
    type: "Grass",
    hp: 393,
    maxHp: 393,
    atk: 308,
    spd: 207,
    moves: ["Mega Drain", "Solar Beam", "Psywave", "Acid"],
    moveType: ["Grass", "Grass", "Psychic", "Poison"],
    moveDmg: [80, 120, 80, 40],
    moveAccuracy: [100, 100, 100, 100],
  },
];

export const pokemonGround = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/golem.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/golem.gif',
    num: 17,
    name: "Golem",
    type: "Rock",
    hp: 407,
    maxHp: 407,
    atk: 312,
    spd: 188,
    moves: ["Rock Slide", "Explosion", "Fire Blast", "Earthquake"],
    moveType: ["Rock", "Normal", "Fire", "Ground"],
    moveDmg: [90, 120, 120, 100],
    moveAccuracy: [90, 70, 70, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/onix.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/onix.gif',
    num: 18,
    name: "Onix",
    type: "Rock",
    hp: 533,
    maxHp: 533,
    atk: 398,
    spd: 111,
    moves: ["Rock Slide", "Dig", "Fire Blast", "Earthquake"],
    moveType: ["Rock", "Rock", "Fire", "Ground"],
    moveDmg: [90, 100, 120, 100],
    moveAccuracy: [90, 100, 70, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/rhydon-f.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/rhydon.gif',
    num: 19,
    name: "Rhydon",
    type: "Ground",
    hp: 408,
    maxHp: 408,
    atk: 394,
    spd: 196,
    moves: ["Earthquake", "Stone Edge", "Hammer Arm", "Dragon Rush"],
    moveType: ["Ground", "Rock", "Fighting", "Dragon"],
    moveDmg: [100, 100, 100, 100],
    moveAccuracy: [100, 80, 90, 75],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/aerodactyl.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/aerodactyl.gif',
    num: 20,
    name: "Aerodactyl",
    type: "Ground",
    hp: 408,
    maxHp: 408,
    atk: 394,
    spd: 196,
    moves: ["Earthquake", "Ancient Power", "Iron Head", "Aerial Ace"],
    moveType: ["Ground", "Rock", "Steel", "Flying"],
    moveDmg: [100, 80, 100, 70],
    moveAccuracy: [100, 100, 100, 100],
  },
];

export const pokemonPsychic = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/alakazam.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/alakazam.gif',
    num: 21,
    name: "Alakazam",
    type: "Psychic",
    hp: 314,
    maxHp: 314,
    atk: 405,
    spd: 372,
    moves: ["Psychic", "Ice Punch", "Giga Impact", "Focus Blast"],
    moveType: ["Psychic", "Ice", "Normal", "Fighting"],
    moveDmg: [90, 75, 150, 120],
    moveAccuracy: [100, 100, 90, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/clefable.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/clefable.gif',
    num: 22,
    name: "Clefable",
    type: "Psychic",
    hp: 393,
    maxHp: 393,
    atk: 238,
    spd: 218,
    moves: ["Psychic", "Ice Punch", "Mega Kick", "Solar Beam"],
    moveType: ["Psychic", "Ice", "Normal", "Grass"],
    moveDmg: [90, 75, 120, 120],
    moveAccuracy: [100, 100, 75, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/hypno.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/hypno.gif',
    num: 23,
    name: "Hypno",
    type: "Psychic",
    hp: 358,
    maxHp: 358,
    atk: 318,
    spd: 325,
    moves: ["Psychic", "Ice Punch", "Submission", "Solar Beam"],
    moveType: ["Psychic", "Ice", "Fighting", "Grass"],
    moveDmg: [90, 75, 80, 120],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/mewtwo.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/mewtwo.gif',
    num: 24,
    name: "Mewtwo",
    type: "Psychic",
    hp: 458,
    maxHp: 458,
    atk: 489,
    spd: 437,
    moves: ["Future Sight", "Thunder Punch", "Psystrike", "Drain Punch"],
    moveType: ["Psychic", "Electric", "Psychic", "Fighting"],
    moveDmg: [120, 75, 100, 80],
    moveAccuracy: [100, 100, 100, 100],
  },
];

export const pokemonGhost = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/gengar.gif',
    num: 25,
    name: "Gengar",
    type: "Ghost",
    hp: 324,
    maxHp: 324,
    atk: 394,
    spd: 350,
    moves: ["Shadow Ball", "Dark Pulse", "Sludge Bomb", "Dream Eater"],
    moveType: ["Ghost", "Dark", "Poison", "Psychic"],
    moveDmg: [80, 80, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/spiritomb.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/spiritomb.gif',
    num: 47,
    name: "Spiritomb",
    type: "Ghost",
    hp: 304,
    maxHp: 304,
    atk: 311,
    spd: 185,
    moves: ["Shadow Ball", "Dark Pulse", "Sludge Bomb", "Dream Eater"],
    moveType: ["Ghost", "Dark", "Poison", "Psychic"],
    moveDmg: [80, 80, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/giratina.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/giratina.gif',
    num: 48,
    name: "Giratina",
    type: "Ghost",
    hp: 523,
    maxHp: 523,
    atk: 566,
    spd: 307,
    moves: ["Shadow Force", "Dragon Claw", "Earth Power", "Draco Meteor"],
    moveType: ["Ghost", "Dragon", "Ground", "Dragon"],
    moveDmg: [80, 80, 90, 130],
    moveAccuracy: [100, 100, 100, 90],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/golurk.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/golurk.gif',
    num: 49,
    name: "Golurk",
    type: "Ghost",
    hp: 383,
    maxHp: 383,
    atk: 383,
    spd: 229,
    moves: ["Dynamic Punch", "Phantom Force", "Hammer Arm", "Earthquake"],
    moveType: ["Ghost", "Ghost", "Fighting", "Ground"],
    moveDmg: [100, 90, 90, 100],
    moveAccuracy: [80, 100, 100, 100],
  },
];

export const pokemonFighting = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/machamp.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/machamp.gif',
    num: 27,
    name: "Machamp",
    type: "Fighting",
    hp: 384,
    maxHp: 384,
    atk: 394,
    spd: 229,
    moves: ["Close Combat", "Thunder Punch", "Stone Edge", "Focus Blast"],
    moveType: ["Fighting", "Electric", "Rock", "Fighting"],
    moveDmg: [120, 75, 100, 120],
    moveAccuracy: [100, 100, 80, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/primeape.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/primeape.gif',
    num: 28,
    name: "Primeape",
    type: "Fighting",
    hp: 333,
    maxHp: 333,
    atk: 308,
    spd: 288,
    moves: ["Close Combat", "Thrash", "Rock Slide", "Low Kick"],
    moveType: ["Fighting", "Normal", "Rock", "Fighting"],
    moveDmg: [120, 90, 75, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonchan.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/hitmonchan.gif',
    num: 29,
    name: "Hitmonchan",
    type: "Fighting",
    hp: 374,
    maxHp: 374,
    atk: 308,
    spd: 345,
    moves: ["Close Combat", "Thrash", "Rock Slide", "Low Kick"],
    moveType: ["Fighting", "Normal", "Rock", "Fighting"],
    moveDmg: [120, 90, 75, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonlee.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/hitmonlee.gif',
    num: 30,
    name: "Hitmonlee",
    type: "Fighting",
    hp: 365,
    maxHp: 365,
    atk: 308,
    spd: 367,
    moves: ["Close Combat", "Thrash", "Rock Slide", "Low Kick"],
    moveType: ["Fighting", "Normal", "Rock", "Fighting"],
    moveDmg: [120, 90, 75, 100],
    moveAccuracy: [100, 100, 90, 100],
  },
];

export const pokemonDragon = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dragonite.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dragonite.gif',
    num: 31,
    name: "Dragonite",
    type: "Dragon",
    hp: 385,
    maxHp: 385,
    atk: 403,
    spd: 302,
    moves: ["Outrage", "Aqua Tail", "Hyper Beam", "Hurricane"],
    moveType: ["Dragon", "Water", "Normal", "Flying"],
    moveDmg: [120, 90, 150, 110],
    moveAccuracy: [100, 90, 90, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/garchomp.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/garchomp.gif',
    num: 32,
    name: "Garchomp",
    type: "Dragon",
    hp: 433,
    maxHp: 433,
    atk: 387,
    spd: 378,
    moves: ["Dragon Rush", "Stone Edge", "Dragon Tail", "Earthquake"],
    moveType: ["Dragon", "Rock", "Dragon", "Ground"],
    moveDmg: [100, 100, 90, 100],
    moveAccuracy: [75, 80, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dialga.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dialga.gif',
    num: 33,
    name: "Dialga",
    type: "Dragon",
    hp: 566,
    maxHp: 566,
    atk: 412,
    spd: 410,
    moves: ["Roar of Time", "Ancient Power", "Ice Beam", "Earthquake"],
    moveType: ["Dragon", "Rock", "Ice", "Ground"],
    moveDmg: [150, 100, 90, 100],
    moveAccuracy: [90, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/palkia.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/palkia.gif',
    num: 34,
    name: "Palkia",
    type: "Dragon",
    hp: 566,
    maxHp: 566,
    atk: 412,
    spd: 409,
    moves: ["Roar of Time", "Hydro Pump", "Ice Beam", "Earthquake"],
    moveType: ["Dragon", "Water", "Ice", "Ground"],
    moveDmg: [150, 120, 90, 100],
    moveAccuracy: [90, 90, 100, 100],
  },
];

export const pokemonPoison = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/arbok.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/arbok.gif',
    num: 35,
    name: "Arbok",
    type: "Poison",
    hp: 323,
    maxHp: 323,
    atk: 286,
    spd: 258,
    moves: ["Rock Slide", "Acid", "Sludge Bomb", "Earthquake"],
    moveType: ["Rock", "Poison", "Poison", "Ground"],
    moveDmg: [75, 40, 90, 100],
    moveAccuracy: [90, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoking.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/nidoking.gif',
    num: 36,
    name: "Nidoking",
    type: "Poison",
    hp: 383,
    maxHp: 383,
    atk: 262,
    spd: 250,
    moves: ["Body Slam", "Ice Beam", "Sludge Bomb", "Earthquake"],
    moveType: ["Normal", "Ice", "Poison", "Ground"],
    moveDmg: [85, 50, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoqueen.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/nidoqueen.gif',
    num: 37,
    name: "Nidoqueen",
    type: "Poison",
    hp: 365,
    maxHp: 365,
    atk: 282,
    spd: 268,
    moves: ["Rock Slide", "Thunder Bolt", "Sludge Bomb", "Fire Blast"],
    moveType: ["Rock", "Electric", "Poison", "Fire"],
    moveDmg: [75, 95, 90, 120],
    moveAccuracy: [90, 100, 100, 85],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/muk.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/muk.gif',
    num: 38,
    name: "Muk",
    type: "Poison",
    hp: 413,
    maxHp: 413,
    atk: 398,
    spd: 148,
    moves: ["Thunder", "Sludge", "Poison Jab", "Fire Blast"],
    moveType: ["Electric", "Poison", "Poison", "Fire"],
    moveDmg: [90, 65, 80, 120],
    moveAccuracy: [100, 100, 100, 85],
  },
];

export const pokemonNormal = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/snorlax.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/snorlax.gif',
    num: 39,
    name: "Snorlax",
    type: "Normal",
    hp: 510,
    maxHp: 510,
    atk: 350,
    spd: 174,
    moves: ["Giga Impact", "Hammer Arm", "Belch", "Blizzard"],
    moveType: ["Normal", "Fighting", "Poison", "Ice"],
    moveDmg: [150, 100, 120, 110],
    moveAccuracy: [90, 90, 90, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeot.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/pidgeot.gif',
    num: 40,
    name: "Pidgeot",
    type: "Normal",
    hp: 369,
    maxHp: 369,
    atk: 248,
    spd: 280,
    moves: ["Fly", "Hyper Beam", "Sky Attack", "Double Edge"],
    moveType: ["Flying", "Normal", "Flying", "Normal"],
    moveDmg: [70, 150, 140, 120],
    moveAccuracy: [95, 90, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/persian.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/persian.gif',
    num: 41,
    name: "Persian",
    type: "Normal",
    hp: 333,
    maxHp: 333,
    atk: 238,
    spd: 328,
    moves: ["Thunder", "Slash", "Skull Bash", "Double Edge"],
    moveType: ["Electric", "Normal", "Normal", "Normal"],
    moveDmg: [120, 70, 100, 120],
    moveAccuracy: [70, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dodrio.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dodrio.gif',
    num: 42,
    name: "Dodrio",
    type: "Normal",
    hp: 322,
    maxHp: 332,
    atk: 233,
    spd: 498,
    moves: ["Thunder", "Sky Attack", "Drill Peck", "Double Edge"],
    moveType: ["Electric", "Flying", "Flying", "Normal"],
    moveDmg: [120, 140, 100, 120],
    moveAccuracy: [70, 90, 100, 100],
  },
];

export const pokemonElectric = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/electivire.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/electivire.gif',
    num: 43,
    name: "Electivire",
    type: "Electric",
    hp: 334,
    maxHp: 334,
    atk: 317,
    spd: 339,
    moves: ["Thunder", "Giga Impact", "Fire Punch", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Fire", "Electric"],
    moveDmg: [110, 150, 75, 90],
    moveAccuracy: [70, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/raichu.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/raichu.gif',
    num: 44,
    name: "Raichu",
    type: "Electric",
    hp: 323,
    maxHp: 323,
    atk: 278,
    spd: 298,
    moves: ["Thunder", "Skull Bash", "Submission", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Fighting", "Electric"],
    moveDmg: [110, 100, 80, 90],
    moveAccuracy: [70, 100, 80, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/magneton.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/magneton.gif',
    num: 45,
    name: "Magneton",
    type: "Electric",
    hp: 303,
    maxHp: 303,
    atk: 318,
    spd: 429,
    moves: ["Thunder Shock", "Skull Bash", "Swift", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Normal", "Electric"],
    moveDmg: [40, 100, 40, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/electrode.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/electrode.gif',
    num: 46,
    name: "Electrode",
    type: "Electric",
    hp: 313,
    maxHp: 313,
    atk: 344,
    spd: 312,
    moves: ["Thunder Shock", "Self Destruct", "Psychic", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Psychic", "Electric"],
    moveDmg: [40, 100, 90, 90],
    moveAccuracy: [100, 100, 100, 100],
  },
];



export const pokemon = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/charizard.gif',
    num: 1,
    name: "Charizard",
    type: "Fire",
    hp: 360,
    maxHp: 360,
    atk: 348,
    spd: 328,
    moves: ["Flamethrower", "Dragon Breath", "Air Slash", "Fire Blast"],
    moveType: ["Fire", "Dragon", "Flying", "Fire"],
    moveDmg: [90, 60, 75, 110],
    moveAccuracy: [100, 100, 95, 85],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/ninetales.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/ninetales.gif',
    num: 2,
    name: "Ninetales",
    type: "Fire",
    hp: 349,
    maxHp: 349,
    atk: 250,
    spd: 298,
    moves: ["Flamethrower", "Dragon Breath", "Hyper Beam", "Dig"],
    moveType: ["Fire", "Dragon", "Normal", "Ground"],
    moveDmg: [90, 60, 150, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/arcanine.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/arcanine.gif',
    num: 3,
    name: "Arcanine",
    type: "Fire",
    hp: 383,
    maxHp: 383,
    atk: 318,
    spd: 288,
    moves: ["Flamethrower", "Dragon Rage", "Take Down", "Dig"],
    moveType: ["Fire", "Dragon", "Normal", "Ground"],
    moveDmg: [90, 90, 90, 100],
    moveAccuracy: [100, 100, 85, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/rapidash.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/rapidash.gif',
    num: 4,
    name: "Rapidash",
    type: "Fire",
    hp: 333,
    maxHp: 333,
    atk: 298,
    spd: 308,
    moves: ["Flamethrower", "Ember", "Swift", "Dig"],
    moveType: ["Fire", "Fire", "Normal", "Ground"],
    moveDmg: [90, 40, 60, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/blastoise.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/blastoise.gif',
    num: 5,
    name: "Blastoise",
    type: "Water",
    hp: 364,
    maxHp: 364,
    atk: 328,
    spd: 284,
    moves: ["Hydro Pump", "Aqua Tail", "Flash Cannon", "Earthquake"],
    moveType: ["Water", "Water", "Steel", "Ground"],
    moveDmg: [110, 90, 80, 100],
    moveAccuracy: [80, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/golduck.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/golduck.gif',
    num: 6,
    name: "Golduck",
    type: "Water",
    hp: 363,
    maxHp: 363,
    atk: 262,
    spd: 268,
    moves: ["Surf", "Aqua Tail", "Submission", "Dig"],
    moveType: ["Water", "Water", "Fighting", "Ground"],
    moveDmg: [95, 90, 80, 100],
    moveAccuracy: [100, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwrath.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/poliwrath.gif',
    num: 7,
    name: "Poliwrath",
    type: "Water",
    hp: 383,
    maxHp: 383,
    atk: 268,
    spd: 238,
    moves: ["Surf", "Ice Beam", "Submission", "Fissure"],
    moveType: ["Water", "Ice", "Fighting", "Ground"],
    moveDmg: [95, 90, 80, 80],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/tentacruel.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/tentacruel.gif',
    num: 8,
    name: "Tentacruel",
    type: "Water",
    hp: 346,
    maxHp: 346,
    atk: 238,
    spd: 298,
    moves: ["Surf", "Ice Beam", "Hydro Pump", "Sludge Bomb"],
    moveType: ["Water", "Ice", "Water", "Poison"],
    moveDmg: [95, 90, 120, 80],
    moveAccuracy: [100, 100, 80, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/slowbro.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/slowbro.gif',
    num: 9,
    name: "Slowbro",
    type: "Water",
    hp: 439,
    maxHp: 439,
    atk: 248,
    spd: 158,
    moves: ["Surf", "Ice Beam", "Thunder Wave", "Psychic"],
    moveType: ["Water", "Ice", "Electric", "Psychic"],
    moveDmg: [95, 90, 90, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dewgong.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dewgong.gif',
    num: 10,
    name: "Dewgong",
    type: "Water",
    hp: 383,
    maxHp: 383,
    atk: 238,
    spd: 345,
    moves: ["Surf", "Ice Beam", "Aurora Beam", "Psychic"],
    moveType: ["Water", "Ice", "Ice", "Psychic"],
    moveDmg: [95, 90, 65, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/cloyster.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/cloyster.gif',
    num: 11,
    name: "Cloyster",
    type: "Water",
    hp: 303,
    maxHp: 303,
    atk: 288,
    spd: 219,
    moves: ["Surf", "Ice Beam", "Blizzard", "Hyper Beam"],
    moveType: ["Water", "Ice", "Ice", "Normal"],
    moveDmg: [95, 90, 120, 120],
    moveAccuracy: [100, 100, 100, 75],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/gyarados.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/gyrados.gif',
    num: 12,
    name: "Gyarados",
    type: "Water",
    hp: 477,
    maxHp: 477,
    atk: 399,
    spd: 232,
    moves: ["Hurricane", "Outrage", "Hydro Pump", "Hyper Beam"],
    moveType: ["Flying", "Dragon", "Water", "Normal"],
    moveDmg: [110, 120, 120, 120],
    moveAccuracy: [70, 100, 80, 75],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/venusaur.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/venusaur.gif',
    num: 13,
    name: "Venusaur",
    type: "Grass",
    hp: 400,
    maxHp: 400,
    atk: 295,
    spd: 280,
    moves: ["Petal Blizzard", "Sludge", "Skull Bash", "Earthquake"],
    moveType: ["Grass", "Poison", "Normal", "Ground"],
    moveDmg: [90, 65, 130, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/vileplume.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/vileplume.gif',
    num: 14,
    name: "Vileplume",
    type: "Grass",
    hp: 353,
    maxHp: 353,
    atk: 358,
    spd: 198,
    moves: ["Solar Beam", "Sludge", "Skull Bash", "Acid"],
    moveType: ["Grass", "Poison", "Normal", "Poison"],
    moveDmg: [120, 65, 130, 40],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/victreebel.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/victreebel.gif',
    num: 15,
    name: "Victreebel",
    type: "Grass",
    hp: 363,
    maxHp: 363,
    atk: 308,
    spd: 238,
    moves: ["Mega Drain", "Razor Leaf", "Skull Bash", "Acid"],
    moveType: ["Grass", "Grass", "Normal", "Poison"],
    moveDmg: [80, 95, 130, 40],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/exeggutor.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/exeggutor.gif',
    num: 16,
    name: "Exeggutor",
    type: "Grass",
    hp: 393,
    maxHp: 393,
    atk: 308,
    spd: 207,
    moves: ["Mega Drain", "Solar Beam", "Psywave", "Acid"],
    moveType: ["Grass", "Grass", "Psychic", "Poison"],
    moveDmg: [80, 120, 80, 40],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/golem.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/golem.gif',
    num: 17,
    name: "Golem",
    type: "Rock",
    hp: 407,
    maxHp: 407,
    atk: 312,
    spd: 188,
    moves: ["Rock Slide", "Explosion", "Fire Blast", "Earthquake"],
    moveType: ["Rock", "Normal", "Fire", "Ground"],
    moveDmg: [90, 120, 120, 100],
    moveAccuracy: [90, 70, 70, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/onix.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/onix.gif',
    num: 18,
    name: "Onix",
    type: "Rock",
    hp: 533,
    maxHp: 533,
    atk: 398,
    spd: 111,
    moves: ["Rock Slide", "Dig", "Fire Blast", "Earthquake"],
    moveType: ["Rock", "Rock", "Fire", "Ground"],
    moveDmg: [90, 100, 120, 100],
    moveAccuracy: [90, 100, 70, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/rhydon-f.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/rhydon.gif',
    num: 19,
    name: "Rhydon",
    type: "Ground",
    hp: 408,
    maxHp: 408,
    atk: 394,
    spd: 196,
    moves: ["Earthquake", "Stone Edge", "Hammer Arm", "Dragon Rush"],
    moveType: ["Ground", "Rock", "Fighting", "Dragon"],
    moveDmg: [100, 100, 100, 100],
    moveAccuracy: [100, 80, 90, 75],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/aerodactyl.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/aerodactyl.gif',
    num: 20,
    name: "Aerodactyl",
    type: "Ground",
    hp: 408,
    maxHp: 408,
    atk: 394,
    spd: 196,
    moves: ["Earthquake", "Ancient Power", "Iron Head", "Aerial Ace"],
    moveType: ["Ground", "Rock", "Steel", "Flying"],
    moveDmg: [100, 80, 100, 70],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/alakazam.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/alakazam.gif',
    num: 21,
    name: "Alakazam",
    type: "Psychic",
    hp: 314,
    maxHp: 314,
    atk: 405,
    spd: 372,
    moves: ["Psychic", "Ice Punch", "Giga Impact", "Focus Blast"],
    moveType: ["Psychic", "Ice", "Normal", "Fighting"],
    moveDmg: [90, 75, 150, 120],
    moveAccuracy: [100, 100, 90, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/clefable.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/clefable.gif',
    num: 22,
    name: "Clefable",
    type: "Psychic",
    hp: 393,
    maxHp: 393,
    atk: 238,
    spd: 218,
    moves: ["Psychic", "Ice Punch", "Mega Kick", "Solar Beam"],
    moveType: ["Psychic", "Ice", "Normal", "Grass"],
    moveDmg: [90, 75, 120, 120],
    moveAccuracy: [100, 100, 75, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/hypno.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/hypno.gif',
    num: 23,
    name: "Hypno",
    type: "Psychic",
    hp: 358,
    maxHp: 358,
    atk: 318,
    spd: 325,
    moves: ["Psychic", "Ice Punch", "Submission", "Solar Beam"],
    moveType: ["Psychic", "Ice", "Fighting", "Grass"],
    moveDmg: [90, 75, 80, 120],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/mewtwo.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/mewtwo.gif',
    num: 24,
    name: "Mewtwo",
    type: "Psychic",
    hp: 458,
    maxHp: 458,
    atk: 489,
    spd: 437,
    moves: ["Future Sight", "Thunder Punch", "Psystrike", "Drain Punch"],
    moveType: ["Psychic", "Electric", "Psychic", "Fighting"],
    moveDmg: [120, 75, 100, 80],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/gengar.gif',
    num: 25,
    name: "Gengar",
    type: "Ghost",
    hp: 324,
    maxHp: 324,
    atk: 394,
    spd: 350,
    moves: ["Shadow Ball", "Dark Pulse", "Sludge Bomb", "Dream Eater"],
    moveType: ["Ghost", "Dark", "Poison", "Psychic"],
    moveDmg: [80, 80, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/gengar.gif',
    num: 26,
    name: "Gengar",
    type: "Ghost",
    hp: 324,
    maxHp: 324,
    atk: 394,
    spd: 350,
    moves: ["Shadow Ball", "Dark Pulse", "Sludge Bomb", "Dream Eater"],
    moveType: ["Ghost", "Dark", "Poison", "Psychic"],
    moveDmg: [80, 80, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/machamp.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/machamp.gif',
    num: 27,
    name: "Machamp",
    type: "Fighting",
    hp: 384,
    maxHp: 384,
    atk: 394,
    spd: 229,
    moves: ["Close Combat", "Thunder Punch", "Stone Edge", "Focus Blast"],
    moveType: ["Fighting", "Electric", "Rock", "Fighting"],
    moveDmg: [120, 75, 100, 120],
    moveAccuracy: [100, 100, 80, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/primeape.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/primeape.gif',
    num: 28,
    name: "Primeape",
    type: "Fighting",
    hp: 333,
    maxHp: 333,
    atk: 308,
    spd: 288,
    moves: ["Close Combat", "Thrash", "Rock Slide", "Low Kick"],
    moveType: ["Fighting", "Normal", "Rock", "Fighting"],
    moveDmg: [120, 90, 75, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonchan.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/hitmonchan.gif',
    num: 29,
    name: "Hitmonchan",
    type: "Fighting",
    hp: 374,
    maxHp: 374,
    atk: 308,
    spd: 345,
    moves: ["Close Combat", "Thrash", "Rock Slide", "Low Kick"],
    moveType: ["Fighting", "Normal", "Rock", "Fighting"],
    moveDmg: [120, 90, 75, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonlee.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/hitmonlee.gif',
    num: 30,
    name: "Hitmonlee",
    type: "Fighting",
    hp: 365,
    maxHp: 365,
    atk: 308,
    spd: 367,
    moves: ["Close Combat", "Thrash", "Rock Slide", "Low Kick"],
    moveType: ["Fighting", "Normal", "Rock", "Fighting"],
    moveDmg: [120, 90, 75, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dragonite.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dragonite.gif',
    num: 31,
    name: "Dragonite",
    type: "Dragon",
    hp: 385,
    maxHp: 385,
    atk: 403,
    spd: 302,
    moves: ["Outrage", "Aqua Tail", "Hyper Beam", "Hurricane"],
    moveType: ["Dragon", "Water", "Normal", "Flying"],
    moveDmg: [120, 90, 150, 110],
    moveAccuracy: [100, 90, 90, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/garchomp.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/garchomp.gif',
    num: 32,
    name: "Garchomp",
    type: "Dragon",
    hp: 433,
    maxHp: 433,
    atk: 387,
    spd: 378,
    moves: ["Dragon Rush", "Stone Edge", "Dragon Tail", "Earthquake"],
    moveType: ["Dragon", "Rock", "Dragon", "Ground"],
    moveDmg: [100, 100, 90, 100],
    moveAccuracy: [75, 80, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dialga.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dialga.gif',
    num: 33,
    name: "Dialga",
    type: "Dragon",
    hp: 566,
    maxHp: 566,
    atk: 412,
    spd: 410,
    moves: ["Roar of Time", "Ancient Power", "Ice Beam", "Earthquake"],
    moveType: ["Dragon", "Rock", "Ice", "Ground"],
    moveDmg: [150, 100, 90, 100],
    moveAccuracy: [90, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/palkia.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/palkia.gif',
    num: 34,
    name: "Palkia",
    type: "Dragon",
    hp: 566,
    maxHp: 566,
    atk: 412,
    spd: 409,
    moves: ["Roar of Time", "Hydro Pump", "Ice Beam", "Earthquake"],
    moveType: ["Dragon", "Water", "Ice", "Ground"],
    moveDmg: [150, 120, 90, 100],
    moveAccuracy: [90, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/arbok.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/arbok.gif',
    num: 35,
    name: "Arbok",
    type: "Poison",
    hp: 323,
    maxHp: 323,
    atk: 286,
    spd: 258,
    moves: ["Rock Slide", "Acid", "Sludge Bomb", "Earthquake"],
    moveType: ["Rock", "Poison", "Poison", "Ground"],
    moveDmg: [75, 40, 90, 100],
    moveAccuracy: [90, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoking.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/nidoking.gif',
    num: 36,
    name: "Nidoking",
    type: "Poison",
    hp: 383,
    maxHp: 383,
    atk: 262,
    spd: 250,
    moves: ["Body Slam", "Ice Beam", "Sludge Bomb", "Earthquake"],
    moveType: ["Normal", "Ice", "Poison", "Ground"],
    moveDmg: [85, 50, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoqueen.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/nidoqueen.gif',
    num: 37,
    name: "Nidoqueen",
    type: "Poison",
    hp: 365,
    maxHp: 365,
    atk: 282,
    spd: 268,
    moves: ["Rock Slide", "Thunder Bolt", "Sludge Bomb", "Fire Blast"],
    moveType: ["Rock", "Electric", "Poison", "Fire"],
    moveDmg: [75, 95, 90, 120],
    moveAccuracy: [90, 100, 100, 85],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/muk.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/muk.gif',
    num: 38,
    name: "Muk",
    type: "Poison",
    hp: 413,
    maxHp: 413,
    atk: 398,
    spd: 148,
    moves: ["Thunder", "Sludge", "Poison Jab", "Fire Blast"],
    moveType: ["Electric", "Poison", "Poison", "Fire"],
    moveDmg: [90, 65, 80, 120],
    moveAccuracy: [100, 100, 100, 85],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/snorlax.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/snorlax.gif',
    num: 39,
    name: "Snorlax",
    type: "Normal",
    hp: 510,
    maxHp: 510,
    atk: 350,
    spd: 174,
    moves: ["Giga Impact", "Hammer Arm", "Belch", "Blizzard"],
    moveType: ["Normal", "Fighting", "Poison", "Ice"],
    moveDmg: [150, 100, 120, 110],
    moveAccuracy: [90, 90, 90, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeot.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/pidgeot.gif',
    num: 40,
    name: "Pidgeot",
    type: "Normal",
    hp: 369,
    maxHp: 369,
    atk: 248,
    spd: 280,
    moves: ["Fly", "Hyper Beam", "Sky Attack", "Double Edge"],
    moveType: ["Flying", "Normal", "Flying", "Normal"],
    moveDmg: [70, 150, 140, 120],
    moveAccuracy: [95, 90, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/persian.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/persian.gif',
    num: 41,
    name: "Persian",
    type: "Normal",
    hp: 333,
    maxHp: 333,
    atk: 238,
    spd: 328,
    moves: ["Thunder", "Slash", "Skull Bash", "Double Edge"],
    moveType: ["Electric", "Normal", "Normal", "Normal"],
    moveDmg: [120, 70, 100, 120],
    moveAccuracy: [70, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dodrio.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dodrio.gif',
    num: 42,
    name: "Dodrio",
    type: "Normal",
    hp: 322,
    maxHp: 332,
    atk: 233,
    spd: 498,
    moves: ["Thunder", "Sky Attack", "Drill Peck", "Double Edge"],
    moveType: ["Electric", "Flying", "Flying", "Normal"],
    moveDmg: [120, 140, 100, 120],
    moveAccuracy: [70, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/electivire.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/electivire.gif',
    num: 43,
    name: "Electivire",
    type: "Electric",
    hp: 334,
    maxHp: 334,
    atk: 317,
    spd: 339,
    moves: ["Thunder", "Giga Impact", "Fire Punch", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Fire", "Electric"],
    moveDmg: [110, 150, 75, 90],
    moveAccuracy: [70, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/raichu.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/raichu.gif',
    num: 44,
    name: "Raichu",
    type: "Electric",
    hp: 323,
    maxHp: 323,
    atk: 278,
    spd: 298,
    moves: ["Thunder", "Skull Bash", "Submission", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Fighting", "Electric"],
    moveDmg: [110, 100, 80, 90],
    moveAccuracy: [70, 100, 80, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/magneton.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/magneton.gif',
    num: 45,
    name: "Magneton",
    type: "Electric",
    hp: 303,
    maxHp: 303,
    atk: 318,
    spd: 429,
    moves: ["Thunder Shock", "Skull Bash", "Swift", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Normal", "Electric"],
    moveDmg: [40, 100, 40, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/electrode.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/electrode.gif',
    num: 46,
    name: "Electrode",
    type: "Electric",
    hp: 313,
    maxHp: 313,
    atk: 344,
    spd: 312,
    moves: ["Thunder Shock", "Self Destruct", "Psychic", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Psychic", "Electric"],
    moveDmg: [40, 100, 90, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/spiritomb.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/spiritomb.gif',
    num: 47,
    name: "Spiritomb",
    type: "Ghost",
    hp: 304,
    maxHp: 304,
    atk: 311,
    spd: 185,
    moves: ["Shadow Ball", "Dark Pulse", "Sludge Bomb", "Dream Eater"],
    moveType: ["Ghost", "Dark", "Poison", "Psychic"],
    moveDmg: [80, 80, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/giratina.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/giratina.gif',
    num: 48,
    name: "Giratina",
    type: "Ghost",
    hp: 523,
    maxHp: 523,
    atk: 566,
    spd: 307,
    moves: ["Shadow Force", "Dragon Claw", "Earth Power", "Draco Meteor"],
    moveType: ["Ghost", "Dragon", "Ground", "Dragon"],
    moveDmg: [80, 80, 90, 130],
    moveAccuracy: [100, 100, 100, 90],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/golurk.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/golurk.gif',
    num: 49,
    name: "Golurk",
    type: "Ghost",
    hp: 383,
    maxHp: 383,
    atk: 383,
    spd: 229,
    moves: ["Dynamic Punch", "Phantom Force", "Hammer Arm", "Earthquake"],
    moveType: ["Ghost", "Ghost", "Fighting", "Ground"],
    moveDmg: [100, 90, 90, 100],
    moveAccuracy: [80, 100, 100, 100],
  },
];
  
export const pokemonData = [
  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/charizard.gif',
    num: 1,
    name: "Charizard",
    type: "Fire",
    hp: 360,
    maxHp: 360,
    atk: 348,
    spd: 328,
    moves: ["Flamethrower", "Dragon Breath", "Air Slash", "Fire Blast"],
    moveType: ["Fire", "Dragon", "Flying", "Fire"],
    moveDmg: [90, 60, 75, 110],
    moveAccuracy: [100, 100, 95, 85],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/ninetales.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/ninetales.gif',
    num: 2,
    name: "Ninetales",
    type: "Fire",
    hp: 349,
    maxHp: 349,
    atk: 250,
    spd: 298,
    moves: ["Flamethrower", "Dragon Breath", "Hyper Beam", "Dig"],
    moveType: ["Fire", "Dragon", "Normal", "Ground"],
    moveDmg: [90, 60, 150, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/arcanine.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/arcanine.gif',
    num: 3,
    name: "Arcanine",
    type: "Fire",
    hp: 383,
    maxHp: 383,
    atk: 318,
    spd: 288,
    moves: ["Flamethrower", "Dragon Rage", "Take Down", "Dig"],
    moveType: ["Fire", "Dragon", "Normal", "Ground"],
    moveDmg: [90, 90, 90, 100],
    moveAccuracy: [100, 100, 85, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/rapidash.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/rapidash.gif',
    num: 4,
    name: "Rapidash",
    type: "Fire",
    hp: 333,
    maxHp: 333,
    atk: 298,
    spd: 308,
    moves: ["Flamethrower", "Ember", "Swift", "Dig"],
    moveType: ["Fire", "Fire", "Normal", "Ground"],
    moveDmg: [90, 40, 60, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/blastoise.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/blastoise.gif',
    num: 5,
    name: "Blastoise",
    type: "Water",
    hp: 364,
    maxHp: 364,
    atk: 328,
    spd: 284,
    moves: ["Hydro Pump", "Aqua Tail", "Flash Cannon", "Earthquake"],
    moveType: ["Water", "Water", "Steel", "Ground"],
    moveDmg: [110, 90, 80, 100],
    moveAccuracy: [80, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/golduck.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/golduck.gif',
    num: 6,
    name: "Golduck",
    type: "Water",
    hp: 363,
    maxHp: 363,
    atk: 262,
    spd: 268,
    moves: ["Surf", "Aqua Tail", "Submission", "Dig"],
    moveType: ["Water", "Water", "Fighting", "Ground"],
    moveDmg: [95, 90, 80, 100],
    moveAccuracy: [100, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwrath.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/poliwrath.gif',
    num: 7,
    name: "Poliwrath",
    type: "Water",
    hp: 383,
    maxHp: 383,
    atk: 268,
    spd: 238,
    moves: ["Surf", "Ice Beam", "Submission", "Fissure"],
    moveType: ["Water", "Ice", "Fighting", "Ground"],
    moveDmg: [95, 90, 80, 80],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/tentacruel.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/tentacruel.gif',
    num: 8,
    name: "Tentacruel",
    type: "Water",
    hp: 346,
    maxHp: 346,
    atk: 238,
    spd: 298,
    moves: ["Surf", "Ice Beam", "Hydro Pump", "Sludge Bomb"],
    moveType: ["Water", "Ice", "Water", "Poison"],
    moveDmg: [95, 90, 120, 80],
    moveAccuracy: [100, 100, 80, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/slowbro.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/slowbro.gif',
    num: 9,
    name: "Slowbro",
    type: "Water",
    hp: 439,
    maxHp: 439,
    atk: 248,
    spd: 158,
    moves: ["Surf", "Ice Beam", "Thunder Wave", "Psychic"],
    moveType: ["Water", "Ice", "Electric", "Psychic"],
    moveDmg: [95, 90, 90, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dewgong.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dewgong.gif',
    num: 10,
    name: "Dewgong",
    type: "Water",
    hp: 383,
    maxHp: 383,
    atk: 238,
    spd: 345,
    moves: ["Surf", "Ice Beam", "Aurora Beam", "Psychic"],
    moveType: ["Water", "Ice", "Ice", "Psychic"],
    moveDmg: [95, 90, 65, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/cloyster.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/cloyster.gif',
    num: 11,
    name: "Cloyster",
    type: "Water",
    hp: 303,
    maxHp: 303,
    atk: 288,
    spd: 219,
    moves: ["Surf", "Ice Beam", "Blizzard", "Hyper Beam"],
    moveType: ["Water", "Ice", "Ice", "Normal"],
    moveDmg: [95, 90, 120, 120],
    moveAccuracy: [100, 100, 100, 75],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/gyarados.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/gyrados.gif',
    num: 12,
    name: "Gyarados",
    type: "Water",
    hp: 477,
    maxHp: 477,
    atk: 399,
    spd: 232,
    moves: ["Hurricane", "Outrage", "Hydro Pump", "Hyper Beam"],
    moveType: ["Flying", "Dragon", "Water", "Normal"],
    moveDmg: [110, 120, 120, 120],
    moveAccuracy: [70, 100, 80, 75],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/venusaur.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/venusaur.gif',
    num: 13,
    name: "Venusaur",
    type: "Grass",
    hp: 400,
    maxHp: 400,
    atk: 295,
    spd: 280,
    moves: ["Petal Blizzard", "Sludge", "Skull Bash", "Earthquake"],
    moveType: ["Grass", "Poison", "Normal", "Ground"],
    moveDmg: [90, 65, 130, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/vileplume.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/vileplume.gif',
    num: 14,
    name: "Vileplume",
    type: "Grass",
    hp: 353,
    maxHp: 353,
    atk: 358,
    spd: 198,
    moves: ["Solar Beam", "Sludge", "Skull Bash", "Acid"],
    moveType: ["Grass", "Poison", "Normal", "Poison"],
    moveDmg: [120, 65, 130, 40],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/victreebel.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/victreebel.gif',
    num: 15,
    name: "Victreebel",
    type: "Grass",
    hp: 363,
    maxHp: 363,
    atk: 308,
    spd: 238,
    moves: ["Mega Drain", "Razor Leaf", "Skull Bash", "Acid"],
    moveType: ["Grass", "Grass", "Normal", "Poison"],
    moveDmg: [80, 95, 130, 40],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/exeggutor.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/exeggutor.gif',
    num: 16,
    name: "Exeggutor",
    type: "Grass",
    hp: 393,
    maxHp: 393,
    atk: 308,
    spd: 207,
    moves: ["Mega Drain", "Solar Beam", "Psywave", "Acid"],
    moveType: ["Grass", "Grass", "Psychic", "Poison"],
    moveDmg: [80, 120, 80, 40],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/golem.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/golem.gif',
    num: 17,
    name: "Golem",
    type: "Rock",
    hp: 407,
    maxHp: 407,
    atk: 312,
    spd: 188,
    moves: ["Rock Slide", "Explosion", "Fire Blast", "Earthquake"],
    moveType: ["Rock", "Normal", "Fire", "Ground"],
    moveDmg: [90, 120, 120, 100],
    moveAccuracy: [90, 70, 70, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/onix.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/onix.gif',
    num: 18,
    name: "Onix",
    type: "Rock",
    hp: 533,
    maxHp: 533,
    atk: 398,
    spd: 111,
    moves: ["Rock Slide", "Dig", "Fire Blast", "Earthquake"],
    moveType: ["Rock", "Rock", "Fire", "Ground"],
    moveDmg: [90, 100, 120, 100],
    moveAccuracy: [90, 100, 70, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/rhydon-f.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/rhydon.gif',
    num: 19,
    name: "Rhydon",
    type: "Ground",
    hp: 408,
    maxHp: 408,
    atk: 394,
    spd: 196,
    moves: ["Earthquake", "Stone Edge", "Hammer Arm", "Dragon Rush"],
    moveType: ["Ground", "Rock", "Fighting", "Dragon"],
    moveDmg: [100, 100, 100, 100],
    moveAccuracy: [100, 80, 90, 75],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/aerodactyl.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/aerodactyl.gif',
    num: 20,
    name: "Aerodactyl",
    type: "Ground",
    hp: 408,
    maxHp: 408,
    atk: 394,
    spd: 196,
    moves: ["Earthquake", "Ancient Power", "Iron Head", "Aerial Ace"],
    moveType: ["Ground", "Rock", "Steel", "Flying"],
    moveDmg: [100, 80, 100, 70],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/alakazam.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/alakazam.gif',
    num: 21,
    name: "Alakazam",
    type: "Psychic",
    hp: 314,
    maxHp: 314,
    atk: 405,
    spd: 372,
    moves: ["Psychic", "Ice Punch", "Giga Impact", "Focus Blast"],
    moveType: ["Psychic", "Ice", "Normal", "Fighting"],
    moveDmg: [90, 75, 150, 120],
    moveAccuracy: [100, 100, 90, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/clefable.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/clefable.gif',
    num: 22,
    name: "Clefable",
    type: "Psychic",
    hp: 393,
    maxHp: 393,
    atk: 238,
    spd: 218,
    moves: ["Psychic", "Ice Punch", "Mega Kick", "Solar Beam"],
    moveType: ["Psychic", "Ice", "Normal", "Grass"],
    moveDmg: [90, 75, 120, 120],
    moveAccuracy: [100, 100, 75, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/hypno.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/hypno.gif',
    num: 23,
    name: "Hypno",
    type: "Psychic",
    hp: 358,
    maxHp: 358,
    atk: 318,
    spd: 325,
    moves: ["Psychic", "Ice Punch", "Submission", "Solar Beam"],
    moveType: ["Psychic", "Ice", "Fighting", "Grass"],
    moveDmg: [90, 75, 80, 120],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/mewtwo.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/mewtwo.gif',
    num: 24,
    name: "Mewtwo",
    type: "Psychic",
    hp: 458,
    maxHp: 458,
    atk: 489,
    spd: 437,
    moves: ["Future Sight", "Thunder Punch", "Psystrike", "Drain Punch"],
    moveType: ["Psychic", "Electric", "Psychic", "Fighting"],
    moveDmg: [120, 75, 100, 80],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/gengar.gif',
    num: 25,
    name: "Gengar",
    type: "Ghost",
    hp: 324,
    maxHp: 324,
    atk: 394,
    spd: 350,
    moves: ["Shadow Ball", "Dark Pulse", "Sludge Bomb", "Dream Eater"],
    moveType: ["Ghost", "Dark", "Poison", "Psychic"],
    moveDmg: [80, 80, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/gengar.gif',
    num: 26,
    name: "Gengar",
    type: "Ghost",
    hp: 324,
    maxHp: 324,
    atk: 394,
    spd: 350,
    moves: ["Shadow Ball", "Dark Pulse", "Sludge Bomb", "Dream Eater"],
    moveType: ["Ghost", "Dark", "Poison", "Psychic"],
    moveDmg: [80, 80, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/machamp.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/machamp.gif',
    num: 27,
    name: "Machamp",
    type: "Fighting",
    hp: 384,
    maxHp: 384,
    atk: 394,
    spd: 229,
    moves: ["Close Combat", "Thunder Punch", "Stone Edge", "Focus Blast"],
    moveType: ["Fighting", "Electric", "Rock", "Fighting"],
    moveDmg: [120, 75, 100, 120],
    moveAccuracy: [100, 100, 80, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/primeape.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/primeape.gif',
    num: 28,
    name: "Primeape",
    type: "Fighting",
    hp: 333,
    maxHp: 333,
    atk: 308,
    spd: 288,
    moves: ["Close Combat", "Thrash", "Rock Slide", "Low Kick"],
    moveType: ["Fighting", "Normal", "Rock", "Fighting"],
    moveDmg: [120, 90, 75, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonchan.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/hitmonchan.gif',
    num: 29,
    name: "Hitmonchan",
    type: "Fighting",
    hp: 374,
    maxHp: 374,
    atk: 308,
    spd: 345,
    moves: ["Close Combat", "Thrash", "Rock Slide", "Low Kick"],
    moveType: ["Fighting", "Normal", "Rock", "Fighting"],
    moveDmg: [120, 90, 75, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonlee.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/hitmonlee.gif',
    num: 30,
    name: "Hitmonlee",
    type: "Fighting",
    hp: 365,
    maxHp: 365,
    atk: 308,
    spd: 367,
    moves: ["Close Combat", "Thrash", "Rock Slide", "Low Kick"],
    moveType: ["Fighting", "Normal", "Rock", "Fighting"],
    moveDmg: [120, 90, 75, 100],
    moveAccuracy: [100, 100, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dragonite.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dragonite.gif',
    num: 31,
    name: "Dragonite",
    type: "Dragon",
    hp: 385,
    maxHp: 385,
    atk: 403,
    spd: 302,
    moves: ["Outrage", "Aqua Tail", "Hyper Beam", "Hurricane"],
    moveType: ["Dragon", "Water", "Normal", "Flying"],
    moveDmg: [120, 90, 150, 110],
    moveAccuracy: [100, 90, 90, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/garchomp.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/garchomp.gif',
    num: 32,
    name: "Garchomp",
    type: "Dragon",
    hp: 433,
    maxHp: 433,
    atk: 387,
    spd: 378,
    moves: ["Dragon Rush", "Stone Edge", "Dragon Tail", "Earthquake"],
    moveType: ["Dragon", "Rock", "Dragon", "Ground"],
    moveDmg: [100, 100, 90, 100],
    moveAccuracy: [75, 80, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dialga.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dialga.gif',
    num: 33,
    name: "Dialga",
    type: "Dragon",
    hp: 566,
    maxHp: 566,
    atk: 412,
    spd: 410,
    moves: ["Roar of Time", "Ancient Power", "Ice Beam", "Earthquake"],
    moveType: ["Dragon", "Rock", "Ice", "Ground"],
    moveDmg: [150, 100, 90, 100],
    moveAccuracy: [90, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/palkia.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/palkia.gif',
    num: 34,
    name: "Palkia",
    type: "Dragon",
    hp: 566,
    maxHp: 566,
    atk: 412,
    spd: 409,
    moves: ["Roar of Time", "Hydro Pump", "Ice Beam", "Earthquake"],
    moveType: ["Dragon", "Water", "Ice", "Ground"],
    moveDmg: [150, 120, 90, 100],
    moveAccuracy: [90, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/arbok.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/arbok.gif',
    num: 35,
    name: "Arbok",
    type: "Poison",
    hp: 323,
    maxHp: 323,
    atk: 286,
    spd: 258,
    moves: ["Rock Slide", "Acid", "Sludge Bomb", "Earthquake"],
    moveType: ["Rock", "Poison", "Poison", "Ground"],
    moveDmg: [75, 40, 90, 100],
    moveAccuracy: [90, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoking.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/nidoking.gif',
    num: 36,
    name: "Nidoking",
    type: "Poison",
    hp: 383,
    maxHp: 383,
    atk: 262,
    spd: 250,
    moves: ["Body Slam", "Ice Beam", "Sludge Bomb", "Earthquake"],
    moveType: ["Normal", "Ice", "Poison", "Ground"],
    moveDmg: [85, 50, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoqueen.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/nidoqueen.gif',
    num: 37,
    name: "Nidoqueen",
    type: "Poison",
    hp: 365,
    maxHp: 365,
    atk: 282,
    spd: 268,
    moves: ["Rock Slide", "Thunder Bolt", "Sludge Bomb", "Fire Blast"],
    moveType: ["Rock", "Electric", "Poison", "Fire"],
    moveDmg: [75, 95, 90, 120],
    moveAccuracy: [90, 100, 100, 85],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/muk.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/muk.gif',
    num: 38,
    name: "Muk",
    type: "Poison",
    hp: 413,
    maxHp: 413,
    atk: 398,
    spd: 148,
    moves: ["Thunder", "Sludge", "Poison Jab", "Fire Blast"],
    moveType: ["Electric", "Poison", "Poison", "Fire"],
    moveDmg: [90, 65, 80, 120],
    moveAccuracy: [100, 100, 100, 85],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/snorlax.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/snorlax.gif',
    num: 39,
    name: "Snorlax",
    type: "Normal",
    hp: 510,
    maxHp: 510,
    atk: 350,
    spd: 174,
    moves: ["Giga Impact", "Hammer Arm", "Belch", "Blizzard"],
    moveType: ["Normal", "Fighting", "Poison", "Ice"],
    moveDmg: [150, 100, 120, 110],
    moveAccuracy: [90, 90, 90, 70],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeot.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/pidgeot.gif',
    num: 40,
    name: "Pidgeot",
    type: "Normal",
    hp: 369,
    maxHp: 369,
    atk: 248,
    spd: 280,
    moves: ["Fly", "Hyper Beam", "Sky Attack", "Double Edge"],
    moveType: ["Flying", "Normal", "Flying", "Normal"],
    moveDmg: [70, 150, 140, 120],
    moveAccuracy: [95, 90, 90, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/persian.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/persian.gif',
    num: 41,
    name: "Persian",
    type: "Normal",
    hp: 333,
    maxHp: 333,
    atk: 238,
    spd: 328,
    moves: ["Thunder", "Slash", "Skull Bash", "Double Edge"],
    moveType: ["Electric", "Normal", "Normal", "Normal"],
    moveDmg: [120, 70, 100, 120],
    moveAccuracy: [70, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/dodrio.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/dodrio.gif',
    num: 42,
    name: "Dodrio",
    type: "Normal",
    hp: 322,
    maxHp: 332,
    atk: 233,
    spd: 498,
    moves: ["Thunder", "Sky Attack", "Drill Peck", "Double Edge"],
    moveType: ["Electric", "Flying", "Flying", "Normal"],
    moveDmg: [120, 140, 100, 120],
    moveAccuracy: [70, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/electivire.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/electivire.gif',
    num: 43,
    name: "Electivire",
    type: "Electric",
    hp: 334,
    maxHp: 334,
    atk: 317,
    spd: 339,
    moves: ["Thunder", "Giga Impact", "Fire Punch", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Fire", "Electric"],
    moveDmg: [110, 150, 75, 90],
    moveAccuracy: [70, 90, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/raichu.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/raichu.gif',
    num: 44,
    name: "Raichu",
    type: "Electric",
    hp: 323,
    maxHp: 323,
    atk: 278,
    spd: 298,
    moves: ["Thunder", "Skull Bash", "Submission", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Fighting", "Electric"],
    moveDmg: [110, 100, 80, 90],
    moveAccuracy: [70, 100, 80, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/magneton.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/magneton.gif',
    num: 45,
    name: "Magneton",
    type: "Electric",
    hp: 303,
    maxHp: 303,
    atk: 318,
    spd: 429,
    moves: ["Thunder Shock", "Skull Bash", "Swift", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Normal", "Electric"],
    moveDmg: [40, 100, 40, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/electrode.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/electrode.gif',
    num: 46,
    name: "Electrode",
    type: "Electric",
    hp: 313,
    maxHp: 313,
    atk: 344,
    spd: 312,
    moves: ["Thunder Shock", "Self Destruct", "Psychic", "Thunderbolt"],
    moveType: ["Electric", "Normal", "Psychic", "Electric"],
    moveDmg: [40, 100, 90, 90],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/spiritomb.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/spiritomb.gif',
    num: 47,
    name: "Spiritomb",
    type: "Ghost",
    hp: 304,
    maxHp: 304,
    atk: 311,
    spd: 185,
    moves: ["Shadow Ball", "Dark Pulse", "Sludge Bomb", "Dream Eater"],
    moveType: ["Ghost", "Dark", "Poison", "Psychic"],
    moveDmg: [80, 80, 90, 100],
    moveAccuracy: [100, 100, 100, 100],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/giratina.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/giratina.gif',
    num: 48,
    name: "Giratina",
    type: "Ghost",
    hp: 523,
    maxHp: 523,
    atk: 566,
    spd: 307,
    moves: ["Shadow Force", "Dragon Claw", "Earth Power", "Draco Meteor"],
    moveType: ["Ghost", "Dragon", "Ground", "Dragon"],
    moveDmg: [80, 80, 90, 130],
    moveAccuracy: [100, 100, 100, 90],
  },

  {
    image: 'https://img.pokemondb.net/sprites/black-white/anim/normal/golurk.gif',
    backImage: 'https://img.pokemondb.net/sprites/black-white/anim/back-normal/golurk.gif',
    num: 49,
    name: "Golurk",
    type: "Ghost",
    hp: 383,
    maxHp: 383,
    atk: 383,
    spd: 229,
    moves: ["Dynamic Punch", "Phantom Force", "Hammer Arm", "Earthquake"],
    moveType: ["Ghost", "Ghost", "Fighting", "Ground"],
    moveDmg: [100, 90, 90, 100],
    moveAccuracy: [80, 100, 100, 100],
  },
];

